[dependencies]
    cangjie_toml = { git = "https://gitcode.com/PermissionDog/cangjie_toml.git" }
[package]
  cjc-version = "0.53.18"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "handy4cj"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
